### ISSUE TITLE
EET, Nahrání certifikátu

### ISSUE THREAD

**Issue by mareksip** [mareksip/anetca-doc#1]
Doplnit návod nahrání certifikátu a vyplnění údajů pro EET

**Comment by ghost** [comment]
Aktivování licence je zde: https://anetca.arrowsys.cz/licence.html
Zkoušel jsem zdokumentovat i vyplnění údajů pro EET, avšak nevím, do jaké kolonky má být vloženo heslo  certifikátu.

**Comment by SipJan-zz** [comment]
EET certifikát a heslo je v anstavení v záložce Konfigurace. 

S pozdravem,

Jan Šíp

**Comment by ghost** [comment]
https://anetca.arrowsys.cz/companyEET.html
