### ISSUE TITLE
Převod a kopírování DB

### ISSUE THREAD

**Issue by mareksip** [mareksip/anetca-doc#2]
Popsat soubory obsahující data a konfig a jak se převádí.

**Comment by ghost** [comment]
Pokud jsem to správně pochopil, tak mám popsat soubor data.config a jeho externí vložení?

**Comment by mareksip** [comment]
Trochu přeformuji, Aby se vytvořila kompletní záloha dat, je pořeba na externí zařízení zkopírovat soubory anetcadbloc.mdf anetcadbloc_log.ldf a data.config.

**Comment by ghost** [comment]
https://anetca.arrowsys.cz/config.html

Stačí to takto, nebo mám ještě něco přidat?

**Comment by mareksip** [comment]
Hotovo

**Comment by SipJan-zz** [comment]
Takhle super. Jen tam prosím vypiš ještě extra ty soubory 3 které se musí vykopírovat

S pozdravem,

Jan Šíp
